
 export const ActionsObject = {
    POST_REGISTER_FORM_DATA : "POST_REGISTER_FORM_DATA",
    POST_LOGIN_FORM_DATA : "POST_LOGIN_FORM_DATA",
    AUTH_SAVE:"AUTH_SAVE",
    AUTH_REMOVE:'AUTH_REMOVE',
    POST_CREATE_POST_FORMDATA:"POST_CREATE_POST_FORMDATA",
    GET_ALL_POST :"GET_ALL_POST",
    SAVE_ALL_POST : "SAVE_ALL_POST",
    DELETE_POST: "DELETE_POST",
    UPDATE_POST :"UPDATE_POST",
    START_LOADER: "START_LOADER",
    STOP_LOADER : "STOP_LOADER"
}


